package com.epam.hr.domain.model;

import java.util.Objects;

public final class Ban extends Entity {
    private final String reason;
    private final long idTarget;
    private final long idAdministrant;
    private final String dateTime;

    private Ban(Ban.Builder builder) {
        super(builder);
        this.reason = builder.reason;
        this.idTarget = builder.idTarget;
        this.idAdministrant = builder.idAdministrant;
        this.dateTime = builder.dateTime;
    }

    public String getReason() {
        return reason;
    }

    public long getIdTarget() {
        return idTarget;
    }

    public long getIdAdministrant() {
        return idAdministrant;
    }

    public String getDateTime() {
        return dateTime;
    }

    /* Autogenerated */
    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("Ban{");
        sb.append("reason='").append(reason).append('\'');
        sb.append(", idTarget=").append(idTarget);
        sb.append(", idAdministrant=").append(idAdministrant);
        sb.append(", dateTime='").append(dateTime).append('\'');
        sb.append(", isValid=").append(isValid);
        sb.append('}');
        return sb.toString();
    }

    /* Autogenerated */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        if (!super.equals(o)) {
            return false;
        }
        Ban ban = (Ban) o;
        return idTarget == ban.idTarget
                && idAdministrant == ban.idAdministrant
                && Objects.equals(reason, ban.reason)
                && Objects.equals(dateTime, ban.dateTime);
    }

    /* Autogenerated */
    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), reason, idTarget, idAdministrant, dateTime);
    }

    public static class Builder extends Entity.Builder<Ban> {
        private String reason;
        private long idTarget;
        private long idAdministrant;
        private String dateTime;

        public Builder setReason(String reason) {
            this.reason = reason;
            return this;
        }

        public Builder setIdTarget(long idTarget) {
            this.idTarget = idTarget;
            return this;
        }

        public Builder setIdAdministrant(long idAdministrant) {
            this.idAdministrant = idAdministrant;
            return this;
        }

        public Builder setDateTime(String dateTime) {
            this.dateTime = dateTime;
            return this;
        }

        public Builder() {
            this(DEFAULT_ID);
        }

        public Builder(long id) {
            super(id);
        }

        public Builder(Ban ban) {
            super(ban);
        }

        @Override
        public Ban build(boolean isValid) {
            this.isValid = isValid;
            return new Ban(this);
        }
    }
}
